#!/bin/bash
#
# Si estás leyendo esto, has traspasado los límites y estás leyendo el código
# que hace funcionar este juego.
#
#                                 ¡Felicidades!                               
#
# La curiosidad juega un papel fundamental en el aprendizaje de Linux, así que
# prueba a leer este código y averiguar qué hace.
#
# En cualquier caso, para continuar jugando, déjate guiar por los pergaminos.
# Si te quedas atascado, ve a GitHub y crea un issue. Estaremos encantados de
# darte pistas.
#

if ! [ -L portal ]; then
    cat << EOF
Una variedad de runas, el idioma de los antiguos místicos que una vez
gobernaron estas tierras, están inscritas en la pared occidental.

EOF
    printf "¿Quieres leerlas?  s/n  "
    read RESP

    if [ "$RESP" = "s" -o "$RESP" = "S" ]; then
        cat << EOF
Recuerdas tus clases con Caitlyn la Verde, quien te enseñó a leer estas
antiguas inscripciones. 

Las runas son instrucciones sobre cómo abrir un portal que te permitirá
atravesar una puerta invisible contenida en la pared.

En Bash, un enlace simbólico (symlink) es un *atajo* a otro archivo o
directorio. Crea uno desde esta habitación a la adyacente escribiendo:

ln -fs ../../../capilla/jardin/pajarera/corredor portal

EOF
    else
        cat << EOF
Será mejor no tocar inscripciones mágicas que no entiendes.

EOF
    fi
else
    cat << EOF
El portal que invocaste sigue abierto de par en par.

Puedes atravesarlo como cualquier otra puerta:

cd portal

EOF
fi



























































































































































































































































































































# Vaya, no ha funcionado.
# Recuerda que los ficheros que terminan en * son aplicaciones.
# Prueba esto:
#
# ./hechizo
