#!/bin/bash
#
# Si estás leyendo esto, has traspasado los límites y estás leyendo el código
# que hace funcionar este juego.
#
#                                 ¡Felicidades!                               
#
# La curiosidad juega un papel fundamental en el aprendizaje de Linux, así que
# prueba a leer este código y averiguar qué hace.
#
# En cualquier caso, para continuar jugando, déjate guiar por los pergaminos.
# Si te quedas atascado, ve a GitHub y crea un issue. Estaremos encantados de
# darte pistas.
#

if ! grep  --only-matching amuleto <<< $I &> /dev/null; then
    cat << EOF
¡Has encontrado un **amuleto** de esmeraldas!"

Para recoger el tesoro, necesitas disponer de una variable en la que guardar
tus pertenencias.

Crea dicha variable (Inventory) y añádele el tesoro escribiendo:

export I=amuleto,\$I

Puedes confirmar que has recogido el tesoro escribiendo:

echo \$I

EOF
    mv ../.capilla ../capilla 2>/dev/null
    mv ../.camara-acorazada ../camara-acorazada 2>/dev/null
    mv ../.fragmento ../fragmento 2>/dev/null
else
    echo "Ya has recogido este tesoro."
fi


















































































































































































































































































# Vaya, no ha funcionado.
# Prueba a visitar el arsenal, ¡quizá puedas volver a por este tesoro más
# tarde!
