#!/bin/bash
#
# Si estás leyendo esto, has traspasado los límites y estás leyendo el código
# que hace funcionar este juego.
#
#                                 ¡Felicidades!                               
#
# La curiosidad juega un papel fundamental en el aprendizaje de Linux, así que
# prueba a leer este código y averiguar qué hace.
#
# En cualquier caso, para continuar jugando, déjate guiar por los pergaminos.
# Si te quedas atascado, ve a GitHub y crea un issue. Estaremos encantados de
# darte pistas.
#

ITEM=espada

if ! grep --quiet "$ITEM" <<< "$I" ; then
    cat << EOF
¡Has encontrado una brillante **espada** de plata! The fascina la habilidad
del herrero que la forjó, y recuerdas las historias de tu infancia sobre el
gran rey místico Rannismir que portaba una espada así para proteger el reino
de los muertos vivientes.

Añade este objeto a tu inventario escribiendo:

export I=$ITEM,\$I

Recuerda que puedes comprobar tu inventario escribiendo:

echo \$I

EOF
    mv ../../.capilla ../../capilla 2>/dev/null
    mv ../../.camara-acorazada ../../camara-acorazada 2>/dev/null
    mv ../../.fragmento ../../fragmento 2>/dev/null
else
    echo "Ya has recogido este tesoro."
fi

























































































































































































































































































# Vaya, no ha funcionado.
#
# Quizá sea de utilidad leer el pergamino.
