#!/bin/bash
#
# Si estás leyendo esto, has traspasado los límites y estás leyendo el código
# que hace funcionar este juego.
#
#                                 ¡Felicidades!                               
#
# La curiosidad juega un papel fundamental en el aprendizaje de Linux, así que
# prueba a leer este código y averiguar qué hace.
#
# En cualquier caso, para continuar jugando, déjate guiar por los pergaminos.
# Si te quedas atascado, ve a GitHub y crea un issue. Estaremos encantados de
# darte pistas.
#

if [[ -e pocion ]]; then
    cat << EOF
Has invocado una poción de curación. Te la bebes rápidamente y sientes cómo
recuperas fuerzas.

Añade 5 HP a tus puntos de vida.

EOF
else
    cat << EOF
Una página de un libro de hechizos de un druida yace en el suelo. Te revela
cómo invocar una poción de curación:

# Para encontrar un fichero en tu sistema, usa el comando find. Por ejemplo,
# para buscar en esta sala: 

find . -name "pocion"

# Una vez que hayas encontrado una poción, cópiala a este directorio y ejecuta
# de nuevo este script.

No hay pociones en esta sala, pero prueba a buscar desde la entrada de la
mazmorra.

Pista: usa el comando pwd para determinar cuántas salas (directorios) hay
entre tu posición actual y la entrada.

EOF

fi


















































































































































































































































































# Vaya, no ha funcionado.
# Recuerda que los ficheros que terminan en * son aplicaciones.
# Prueba esto:
#
# ./hechizo
