#!/bin/bash
#
# Si estás leyendo esto, has traspasado los límites y estás leyendo el código
# que hace funcionar este juego.
#
#                                 ¡Felicidades!                               
#
# La curiosidad juega un papel fundamental en el aprendizaje de Linux, así que
# prueba a leer este código y averiguar qué hace.
#
# En cualquier caso, para continuar jugando, déjate guiar por los pergaminos.
# Si te quedas atascado, ve a GitHub y crea un issue. Estaremos encantados de
# darte pistas.
#

if [ -e mago-oscuro ]; then
    cat << EOF
El antiguo mago, Arnnisen el Gris, se aparece ante tus ojos.
¡Lo has liberado, y ahora lucha a tu lado contra el caos reptante!

EOF
else
    cat << EOF
Sientes una presencia.
Probablemente sea tu imaginación.

EOF
fi


















































































































































































































































































# Vaya, no ha funcionado.
# Recuerda que los ficheros que terminan en * son aplicaciones.
# Prueba esto:
#
# ./luz-magica
#
# Si no ves el * después del nombre del fichero, posiblemente te hayas
# olvidado de usar ls -F
