#!/bin/bash
#
# Si estás leyendo esto, has traspasado los límites y estás leyendo el código
# que hace funcionar este juego.
#
#                                 ¡Felicidades!                               
#
# La curiosidad juega un papel fundamental en el aprendizaje de Linux, así que
# prueba a leer este código y averiguar qué hace.
#
# En cualquier caso, para continuar jugando, déjate guiar por los pergaminos.
# Si te quedas atascado, ve a GitHub y crea un issue. Estaremos encantados de
# darte pistas.
#

if [ -e tambor ]; then
    cat << EOF
Tambores de guerra retumban a lo lejos, dando fuerza a Nyarlathotep. 

Si conoces un hechizo para hacer desaparecer los tambores, ¡Nyarlathotep
debería debilitarse! Busca el comando "mv" o "rm".

EOF
else
    cat << EOF
Los tambores se han callado. ¡Es tu oportunidad de atacar!

EOF
fi


















































































































































































































































































# Vaya, no ha funcionado.
# Recuerda que los ficheros que terminan en * son aplicaciones.
# Prueba esto:
#
# ./percusionista
#
# Si no ves el * después del nombre del fichero, posiblemente te hayas
# olvidado de usar ls -F
